---
dependencies:
  finance_kline_core: ^0.0.3
description: '''A interface library for market data providers.'''
dev_dependencies:
  auto_exporter: ^4.0.0
  build_runner: ^2.6.0
  test: ^1.24.0
  very_good_analysis: any
environment:
  sdk: ^3.0.0
homepage: https://github.com/normidar/market_interface
name: market_interface
topics:
  - finance
  - kline
  - market
  - data
  - api
version: 0.0.1