---
dependencies: null
description: "'A pkg in Coin Galaxy.'"
dev_dependencies:
  auto_exporter: ^4.0.0
  build_runner: ^2.6.0
  test: ^1.24.0
  very_good_analysis: any
environment:
  sdk: ^3.0.0
name: market_interface
homepage: https://github.com/normidar/market_interface
topics:
  - a
  - b
  - c
  - d
  - e
version: 0.0.1
